### PR TITLE
make font color lighter

### PR DESCRIPTION
**Pull request by behroozbc**
https://github.com/ghost1372/ghost1372.github.io/issues/2

### CODE REVIEW

**Comment by ghost1372** [comment]
thank you, but i should reject this pr Because your changes will be temporary and will disappear with the next commit

**Comment by behroozbc** [comment]
okay I want to change [this](https://github.com/ghost1372/HandyControl-English-Doc) but where I must change to apply 
I can connect you in telegram ?

**Comment by ghost1372** [comment]
There was a problem and the theme files were not uploaded (because the theme itself uses the git) I just deleted the project to fix the problem

tg: @KlausM72

**Comment by behroozbc** [comment]
okay.
I send you message in telegram. 
I wait when upload project

**Pull request closed without merging**
